server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8082/
          predicates:
            - Path=/products/**